spring:
  application:
    name: customer-api
  datasource:
    url: jdbc:postgresql://localhost:5433/customerdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info